

const conselhos_1 = [
    "Seja gentil consigo mesmo.",
    "Priorize a saúde física e mental.",
    "Aprenda algo novo todos os dias.",
    "Mantenha uma rotina de sono consistente.",
    "Pratique gratidão diariamente.",
    "Seja paciente com o processo de crescimento pessoal.",
    "Busque o equilíbrio entre trabalho e lazer.",
    "Escute mais e fale menos.",
    "Mantenha-se hidratado.",
    "Encontre tempo para a meditação ou a reflexão tranquila.",
    "Cuide de suas amizades verdadeiras.",
    "Seja proativo na resolução de conflitos.",
    "Acredite em si mesmo e em suas habilidades.",
    "Valorize o tempo com sua família.",
    "Aprenda a dizer 'não' quando necessário.",
    "Sorria sempre que puder.",
    "Evite julgar os outros.",
    "Estabeleça metas claras para si mesmo.",
    "Fique presente e no momento.",
    "Respire profundamente durante momentos de estresse.",
    "Leia livros que o inspirem.",
    "Mantenha-se fiel aos seus valores.",
    "Pratique a empatia e a compaixão.",
    "Aprenda com seus erros e veja-os como oportunidades de crescimento.",
    "Pratique a autocompaixão.",
    "Aprenda a administrar suas finanças pessoais.",
    "Dedique tempo para hobbies que o façam feliz.",
    "Seja honesto consigo mesmo e com os outros.",
    "Mantenha-se aberto a novas perspectivas e ideias.",
    "Aprecie a beleza da natureza.",
    "Expresse sua gratidão aos outros.",
    "Pratique o perdão e deixe o passado para trás.",
    "Acredite que você é capaz de superar desafios.",
    "Mantenha um diário para refletir sobre suas emoções.",
    "Conecte-se com pessoas que o apoiam.",
    "Aceite que nem sempre você pode controlar tudo.",
    "Mantenha-se flexível e adaptável às mudanças.",
    "Respeite as opiniões diferentes das suas.",
    "Celebre suas conquistas, não importa quão pequenas elas sejam.",
    "Aprenda a lidar com críticas construtivas.",
    "Dê-se permissão para descansar quando estiver cansado.",
    "Enfrente seus medos e desafie-se a crescer.",
    "Valorize seu tempo e energia.",
    "Pratique a moderação em todas as áreas da vida.",
    "Concentre-se no que você pode controlar e deixe ir o resto.",
    "Seja flexível e adaptável às mudanças.",
    "Respeite suas necessidades emocionais e tire um tempo para processar suas emoções.",
    "Acredite que você merece amor e felicidade.",
    "Faça uma pausa e respire fundo em momentos de estresse.",
    "Aprenda a filtrar informações e focar no que é importante.",
    "Aprecie a simplicidade e a beleza das coisas cotidianas."
]

const conselhos_2 = [
    "Pratique a paciência em situações desafiadoras.",
    "Dê-se permissão para descansar quando necessário.",
    "Aprenda a se perdoar por erros passados.",
    "Seja humilde e aberto a aprender com os outros.",
    "Valorize a importância do autocuidado.",
    "Aceite que a vida é cheia de altos e baixos.",
    "Encontre inspiração em pessoas que o motivam.",
    "Mantenha uma mentalidade de crescimento constante.",
    "Pratique a comunicação assertiva.",
    "Enfrente seus medos e tome medidas corajosas.",
    "Acredite que você tem o poder de criar mudanças positivas em sua vida.",
    "Mantenha-se organizado para aumentar sua produtividade.",
    "Aprenda a delegar tarefas e confiar nos outros.",
    "Seja grato pelas pequenas coisas da vida.",
    "Pratique a resiliência em face de desafios.",
    "Valorize o poder da empatia em suas interações.",
    "Dê um passo de cada vez em direção a seus objetivos.",
    "Acredite em sua capacidade de superar adversidades.",
    "Mantenha-se flexível e aberto a novas possibilidades.",
    "Pratique a honestidade consigo mesmo e com os outros.",
    "Encontre tempo para relaxar e recarregar suas energias.",
    "Aprecie a beleza da arte e da criatividade.",
    "Aceite que as mudanças fazem parte da vida.",
    "Valorize o tempo de qualidade com seus entes queridos.",
    "Dê importância à sua intuição e sabedoria interior.",
    "Pratique a compreensão e o respeito pelas diferentes culturas.",
    "Mantenha-se comprometido com seus objetivos, mesmo diante de obstáculos.",
    "Acredite em sua capacidade de fazer uma diferença positiva no mundo.",
    "Seja gentil com os outros, pois você nunca sabe o que estão enfrentando.",
    "Valorize o poder da educação e do aprendizado contínuo.",
    "Pratique a autenticidade e seja verdadeiro consigo mesmo.",
    "Dê um passo para fora de sua zona de conforto para experimentar o crescimento.",
    "Aprenda a aceitar elogios com gratidão.",
    "Mantenha-se aberto a novas amizades e conexões.",
    "Acredite que você merece amor e felicidade.",
    "Seja paciente consigo mesmo enquanto busca seus objetivos.",
    "Valorize a importância de ter um tempo para si mesmo.",
    "Pratique a autodisciplina para alcançar seus objetivos.",
    "Dê-se permissão para pedir ajuda quando precisar.",
    "Aprenda a dizer 'sim' para oportunidades que o desafiam a crescer.",
    "Mantenha-se focado em suas prioridades e metas.",
    "Aprecie a jornada, mesmo quando os resultados não são imediatos.",
    "Aceite que a perfeição é uma ilusão e está tudo bem cometer erros.",
    "Valorize a diversidade e respeite as diferenças.",
    "Esteja presente em suas interações com os outros.",
    "Dê valor ao tempo que você passa com seus entes queridos.",
    "Acredite em sua capacidade de superar dificuldades.",
    "Aceite que nem tudo está sob seu controle e aprenda a soltar.",
    "Pratique a gratidão diária pelos aspectos positivos de sua vida.",
    "Seja gentil e compreensivo consigo mesmo em momentos de desafio.",
    "Acredite que você é digno de amor e respeito.",
    "Encontre significado e propósito em suas ações e escolhas.",
    "Dê um passo para trás e reflita antes de reagir impulsivamente.",
    "Pratique a resolução construtiva de conflitos em suas relações.",
    "Valorize o poder da empatia e da compaixão pelos outros."
]


const conselhos_3 = [
    "Aprenda a enfrentar desafios com otimismo e perseverança.",
    "Dê importância ao autocuidado e à saúde mental.",
    "Pratique a paciência em momentos de adversidade.",
    "Seja aberto a novas oportunidades e experiências.",
    "Valorize a importância da comunicação clara e eficaz.",
    "Acredite em sua capacidade de alcançar seus objetivos.",
    "Mantenha-se positivo mesmo diante de desafios.",
    "Aprenda a se adaptar a mudanças e incertezas.",
    "Dê um passo fora de sua zona de conforto para crescer.",
    "Pratique a autenticidade e seja verdadeiro consigo mesmo.",
    "Encontre tempo para se reconectar com a natureza.",
    "Aceite que é normal cometer erros e aprender com eles.",
    "Valorize a importância de se cercar de pessoas positivas.",
    "Seja grato pelas lições que a vida lhe oferece.",
    "Acredite em sua intuição e sabedoria interior.",
    "Mantenha-se comprometido com suas metas e sonhos.",
    "Pratique a compaixão e seja gentil com os outros.",
    "Dê valor à importância do descanso e da recuperação.",
    "Aprenda a liberar ressentimentos e perdoar.",
    "Mantenha-se fiel a seus valores e princípios.",
    "Acredite que você merece amor e felicidade.",
    "Pratique a resiliência em face de adversidades.",
    "Dê-se permissão para buscar ajuda quando precisar.",
    "Enfrente seus medos e abrace a coragem.",
    "Valorize a importância de encontrar tempo para si mesmo.",
    "Seja aberto a aprender com pessoas de diferentes perspectivas.",
    "Acredite em sua própria força e poder interior.",
    "Pratique a humildade e esteja disposto a crescer.",
    "Dê um passo para trás e respire profundamente em momentos de estresse.",
    "Mantenha uma mentalidade de crescimento e aprendizado contínuo.",
    "Aprenda a dizer 'sim' para novas oportunidades.",
    "Valorize a importância de se expressar autenticamente.",
    "Pratique a aceitação de si mesmo e dos outros.",
    "Dê valor à importância de se conectar com sua intuição.",
    "Acredite em sua capacidade de superar desafios.",
    "Seja gentil e compreensivo consigo mesmo em momentos de dificuldade.",
    "Pratique a gratidão diariamente pelos aspectos positivos da vida.",
    "Valorize a importância de estabelecer limites saudáveis.",
    "Esteja presente no momento e pratique a atenção plena.",
    "Aprenda a perdoar a si mesmo e aos outros.",
    "Seja corajoso ao enfrentar mudanças e incertezas.",
    "Dê-se permissão para desfrutar de momentos de lazer e diversão.",
    "Valorize a importância de se expressar de forma clara e respeitosa.",
    "Pratique a gentileza em suas interações diárias.",
    "Acredite que você é capaz de alcançar seus sonhos.",
    "Mantenha-se positivo mesmo diante de desafios.",
    "Aprenda a deixar ir o que não está mais servindo em sua vida.",
    "Seja aberto a aprender com seus erros e fracassos.",
    "Pratique a empatia e tente entender as perspectivas dos outros.",
    "Dê valor à importância de se cercar de apoio emocional.",
    "Esteja disposto a se comprometer com o crescimento pessoal.",
    "Acredite em sua capacidade de criar uma vida significativa.",
    "Mantenha-se resiliente e forte diante de obstáculos.",
    "Pratique a autodisciplina em busca de seus objetivos.",
]

const conselhos_4 = [
    "Dê-se permissão para ser vulnerável e autêntico.",
    "Valorize a importância de ser gentil consigo mesmo.",
    "Aprenda a dizer 'não' quando necessário para preservar sua energia.",
    "Seja grato pelas pequenas alegrias da vida.",
    "Pratique a compreensão e o respeito pelas diferenças dos outros.",
    "Dê valor à importância de se manter presente e no momento.",
    "Acredite em sua capacidade de enfrentar desafios com coragem.",
    "Mantenha-se curioso e aberto a novas experiências.",
    "Pratique a paciência e a tolerância em suas interações.",
    "Esteja disposto a se adaptar a mudanças e incertezas.",
    "Valorize a importância de se cercar de pessoas que o apoiam.",
    "Seja autêntico em suas ações e escolhas.",
    "Aprenda a se perdoar por erros passados e seguir em frente.",
    "Mantenha-se flexível e aberto a diferentes perspectivas.",
    "Pratique a gratidão diária pelos aspectos positivos da vida.",
    "Dê-se permissão para cuidar de si mesmo e de suas necessidades.",
    "Valorize a importância de se expressar de forma honesta e respeitosa.",
    "Acredite em sua capacidade de superar obstáculos e alcançar seus objetivos.",
    "Mantenha-se fiel a seus valores e princípios.",
    "Pratique a empatia e tente entender os sentimentos dos outros.",
    "Seja gentil com os outros e espalhe bondade sempre que possível.",
    "Aprenda a aceitar elogios com gratidão e humildade.",
    "Valorize a importância de ser autêntico em suas interações.",
    "Pratique a resiliência e a capacidade de se recuperar de adversidades.",
    "Dê valor à importância de ter um tempo para si mesmo e relaxar.",
    "Esteja disposto a pedir ajuda quando precisar e oferecer ajuda aos outros.",
    "Acredite em sua capacidade de criar uma vida significativa e com propósito.",
    "Mantenha-se positivo mesmo diante de desafios e contratempos.",
    "Pratique a paciência e o autocontrole em situações estressantes.",
    "Seja grato pelas lições que a vida lhe ensina.",
    "Valorize a importância de se conectar com seus valores e propósito.",
    "Aprenda a se adaptar a mudanças e abraçar a incerteza.",
    "Mantenha-se presente e no momento para apreciar a vida.",
    "Pratique a compaixão consigo mesmo e com os outros.",
    "Dê-se permissão para crescer e evoluir como pessoa.",
    "Valorize a importância de ter relacionamentos saudáveis e significativos.",
    "Seja gentil com os outros e espalhe bondade pelo mundo.",
    "Acredite em sua capacidade de enfrentar desafios e superar obstáculos.",
    "Mantenha-se fiel a seus valores e não comprometa sua integridade.",
    "Pratique a empatia e tente entender as perspectivas dos outros.",
    "Dê importância à sua saúde física e mental.",
    "Aprenda a se perdoar e liberar-se de culpa passada.",
    "Valorize a importância de ser autêntico e genuíno.",
    "Seja grato pelas pequenas alegrias e momentos de felicidade.",
    "Pratique a paciência e evite reações impulsivas.",
    "Mantenha-se aberto a aprender e crescer ao longo da vida.",
    "Dê-se permissão para tirar um tempo para si mesmo e descansar.",
    "Valorize a importância de ter uma mentalidade de crescimento.",
    "Acredite em sua capacidade de criar uma vida significativa.",
    "Pratique a compaixão e seja gentil consigo mesmo.",
    "Seja corajoso em enfrentar seus medos e desafios.",
    "Mantenha-se positivo e otimista mesmo em tempos difíceis.",
    "Pratique a gratidão diária pelos aspectos positivos da vida.",
    "Dê-se permissão para pedir ajuda e apoio quando precisar.",
    "Valorize a importância de se cercar de pessoas que o apoiam.",
]


export const conselhos = [
    // Array de conselhos
    conselhos_1,
    conselhos_2,
    conselhos_3,
    conselhos_4
];
